# Generated by Django 5.0.4 on 2024-04-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioContent',
            fields=[
                ('entity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('entity_summary', models.TextField()),
                ('date_month', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.TextField()),
                ('date_month', models.CharField(max_length=50)),
                ('src', models.TextField()),
                ('alt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('entity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('bio_content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mnemo_api.biocontent')),
            ],
        ),
        migrations.AddField(
            model_name='biocontent',
            name='diary_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mnemo_api.diaryentry'),
        ),
        migrations.AddField(
            model_name='biocontent',
            name='images',
            field=models.ManyToManyField(blank=True, to='mnemo_api.image'),
        ),
    ]
