# Generated by Django 5.0.4 on 2024-04-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnemo_api', '0002_alter_biocontent_diary_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biocontent',
            name='diary_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mnemo_api.diaryentry'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='bio_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mnemo_api.biocontent'),
        ),
    ]
