# Generated by Django 5.0.4 on 2024-04-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnemo_api', '0004_alter_image_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
